apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: specificnamespace
  name: read-write
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
